#!/bin/bash
rm -rf build-verif
mkdir -p build-verif


# Copy VRASED's Verilog source code to temp directory
cp ../openmsp430/msp_core/openMSP430_undefines.v ./build-verif/
cp ../openmsp430/msp_core/openMSP430_defines.v ./build-verif/
cp ../vrased/hw-mod/*.v ./build-verif/
# Specification
cp ../verification_specs/ltl_specs.smv ./build-verif

for filename in ./build-verif/*.v; do
	sed -i "s/always @(posedge clk)/always @(*)/g" $filename
done

sh ./verif-tools/verilog2smv.sh ./build-verif/hwmod.v ./build-verif/hwmod_generated.smv hwmod

sed -i "s/IVAR/VAR/g" ./build-verif/hwmod_generated.smv # Hacky here since IVAR doesnt work properly
echo '#include "ltl_specs.smv"' >> ./build-verif/hwmod_generated.smv

#./verif-tools/NuSMV  -v 2 -pre cpp ./build-verif/hwmod_generated.smv
#./verif-tools/NuSMV -coi -df -dcx -pre cpp ./build-verif/hwmod_generated.smv
#./verif-tools/NuSMV -i order.ord -coi -dcx -df -v 1 -pre cpp ./build-verif/hwmod_generated.smv
./verif-tools/NuSMV -coi -dcx -df -v 1 -pre cpp ./build-verif/hwmod_generated.smv
#./verif-tools/NuSMV -ctt -v 1 -pre cpp ./build-verif/hwmod_generated.smv
#./verif-tools/NuSMV -bmc -bmc_length 10 -v 1 -pre cpp ./build-verif/hwmod_generated.smv

#rm -rf build-verif
